### ISSUE TITLE
Can you provide Arduino nano sketch ?

### ISSUE THREAD

**Issue by dexterbot80** [hannahvsawiuk/3-Phase-PWM#1]
Hi,
I appreciate your work for the AC 3 phase motor controller.
Can you publish the arduino nano sketch?
Do you think you could develop such a three-phase pure sine arduino controller from 10Hz to 400Hz ?
All the best from Romania

**Comment by hannahvsawiuk** [comment]
Hi! I apologize for the very very late reply. Within the README, there is a link to a full report. On the last page, there is a schematic for the hardware layout including the wiring of the microcontroller. In terms of the frequency, do you mean the full range (variable frequency), or static? 

For a static frequency, a few values in the code need to be changed to read the LUT at the desired speed. Further, the table needs to be reproduced for the frequency to maintain an appropriate resolution.

For variable, I suggest using the math functions. When a change in frequency is initiated, the process would need to be suspended while the dynamic LUT is reconfigured for the given frequency to maintain signal integrity. Another option would be to determine the relative starting value and to calculate the incrementation value. Or, built-in math functions could be used to determine the value for every update, which could be implemented in the current output compare value updating interrupt service routine. I am unsure of the amount of overhead of each option, but it would require some testing.

**Comment by hannahvsawiuk** [comment]
I have not revisited this project in 2 years but I would like to rework it to improve the functionality and to also integrate the option for variable frequency. This would be necessary for an AC speed drive.

**Comment by hannahvsawiuk** [comment]
Reopened if you have any more questions @dexterbot80
